kijho_mailer_homepage:
    path:     /home
    defaults: { _controller: KijhoMailerBundle:Default:home }
    
kijho_mailer_layout:
    resource: "@KijhoMailerBundle/Resources/config/routing/layout.yml"
    prefix:   /layouts
    
kijho_mailer_template:
    resource: "@KijhoMailerBundle/Resources/config/routing/template.yml"
    prefix:   /templates

kijho_mailer_template_group:
    resource: "@KijhoMailerBundle/Resources/config/routing/templateGroup.yml"
    prefix:   /templateGroups
    
kijho_mailer_settings:
    resource: "@KijhoMailerBundle/Resources/config/routing/settings.yml"
    prefix:   /settings
    
kijho_mailer_email_event:
    resource: "@KijhoMailerBundle/Resources/config/routing/emailEvent.yml"
    prefix:   /emailEvents
